server:
  servlet:
    application-display-name: SAKPaaS
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: SAKPaaS
app:
  presence:
    duration: 20
  version: 1.3.8
management:
  server:
    port: 9000
  endpoints:
    web:
      exposure:
        include: "*"
