server:
  servlet:
    application-display-name: SAKPaaS
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: SAKPaaS
app:
  presence:
    duration: 20
  occupancy:
    duration: 300
  version: dev
  commit: dev
management:
  server:
    port: 9000
  endpoints:
    web:
      exposure:
        include: "*"
keycloak:
  auth-server-url: <Address of the cool Keycloak instance (ask Robert)>
  realm: <super cool realm (ask Robert)>
  resource: <mega cool resource (ask Robert)>
  ssl-required: external
  credentials:
    secret: <Super Secret Client Secret (ask Robert)>
  bearer-only: true
  securityConstraints:
    - authRoles:
        - uma_authorization
      securityCollections:
        - patterns: /auth/*
    - securityCollections:
        - patterns: /v1/*
        - patterns: /v2/*
        - patterns: /
