server:
  servlet:
    context-path: /sakpaas
    application-display-name: SAKPaaS
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: zuschwer
app:
  presence:
    duration: 20