server:
  servlet:
    application-display-name: SAKPaaS
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: SAKPaaS
app:
  presence:
    duration: 20
  occupancy:
    duration: 300
  version: dev
  commit: dev
management:
  server:
    port: 9000
  endpoints:
    web:
      exposure:
        include: "*"
keycloak:
  auth-server-url: https://auth.happyhamster.org/auth/
  realm: dev
  resource: backend
  ssl-required: external
  credentials:
    secret: ad345d06-301d-49ab-b1d1-5de0eeb20eb3
  bearer-only: true
  securityConstraints:
    - authRoles:
        - uma_authorization
      securityCollections:
        - patterns: /auth/*
    - securityCollections:
        - patterns: /v1/*
        - patterns: /v2/*
        - patterns: /