name: Integration (Scale down)

on:
  pull_request:
    types:
      - closed

jobs:
  environment:
    name: Environment
    runs-on: ubuntu-latest
    if: startsWith(github.event.pull_request.head.ref, 'release/')

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          repository: 'SAKPaaS/deployment'

      - name: Scale down (backend)
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: scale --replicas=0 -f backend/integration/deployment.yaml || true

      - name: Scale down (support)
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: scale --replicas=0 -f backend/integration/support/stateful-set.yaml || true

      - name: Delete PersistentVolumeClaim
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: delete -f backend/integration/support/persistent-volume-claim.yaml || true
